#can be used instead of Platform Project (my-project/gradle/platform)

[libraries]
commons-lang = "org.apache.commons:commons-lang3:3.17.0"
slf4j-api = "org.slf4j:slf4j-api:2.0.16"
slf4j-simple = "org.slf4j:slf4j-simple:2.0.16"